version: '3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres/schema_djangoapp.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - logs:/var/logs/
    networks:
      - db_network

  web:
    build:
      context: fintastic_project
    command: bash -c "/init/local_entrypoint.sh"
    env_file:
      - .env
    ports:
      - 8001:8000
    volumes:
      - ./fintastic_project/src:/code
      - ./fintastic_project/gunicorn:/code/gunicorn
      - staticfiles:/code/staticfiles
      - media:/code/media
      - logs:/var/logs/
    depends_on:
      - db
    networks:
      - db_network
      - nginx_network

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles:/code/static:ro
      - media:/code/media:ro
      - logs:/var/logs/
    env_file:
      - .env
    networks:
      - nginx_network
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles:
  media:
  logs:

networks:
  db_network:
    driver: bridge
  nginx_network:
    driver: bridge
