# Generated by Django 3.1.3 on 2020-11-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True, verbose_name='Reference')),
                ('account', models.CharField(max_length=64, verbose_name='Account')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount')),
                ('type', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=16, verbose_name='Type')),
                ('category', models.CharField(max_length=32, verbose_name='Category')),
            ],
        ),
    ]
